language: cpp

dist: xenial
env:
    TEST_ROOT_PATH=${HOME}/build/buddytian/travis_test

#default before_install, clone Ascend/tools as default, it can be overwrited by jobs
#before_install: python3 ${BUILD_ROOT_PATH}/install/install.py before_install_clone_tools

#default install, it can be overwrited by jobs
#install: python3 ${BUILD_ROOT_PATH}/install/install.py install

jobs:
    include:
        - stage: ascenddk test
          name: "ascenddk test"
          #no need to do clone tools
          #before_install: python3 ${BUILD_ROOT_PATH}/install/install.py before_install
          install: sudo apt-get -y install sshpass
          before_script: sudo ifconfig ens4:0 192.168.1.71 broadcast 192.168.1.1 netmask 255.255.255.0
          #script: ${TEST_ROOT_PATH}/ascenddk/scripts/travis_scripts/comm/ssh_ubuntu.sh
          script: ifconfig
        - name: "ascenddk test1"
          #no need to do clone tools
          #before_install: python3 ${BUILD_ROOT_PATH}/install/install.py before_install
          #install: python3 ${BUILD_ROOT_PATH}/install/install.py install_pylint
          before_script: ifconfig ens4:0 down
          script: ifconfig
